#!/bin/bash

# Variables (match it with config.mk)
PREFIX="/usr/local"
APPPREFIX="$PREFIX/share/applications"
MANPREFIX="$PREFIX/share/man"
FONTPREFIX="$PREFIX/share/fonts"
NAUTILUS_EXT="/usr/share/nautilus-python/extensions"
TMPDIR="/tmp/st-appdir.$RANDOM"

# Font list (format: "Name URL")
fonts=(
	"Firacode https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.tar.xz"
	"Firamono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.tar.xz"
	"Ubuntumono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.tar.xz"
	"LiterationMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/LiberationMono.tar.xz"
	"Caskaydiacove https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.tar.xz"
	"Caskaydiamono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.tar.xz"
	"Hack https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz"
	"Inconsolata https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Inconsolata.tar.xz"
	"Iosevka https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Iosevka.tar.xz"
	"Iosevkaterm https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IosevkaTerm.tar.xz"
	"Iosevkatermslab https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IosevkaTermSlab.tar.xz"
	"Jetbrainsmono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz"
	"Meslolgm https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.tar.xz"
	"Robotomono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/RobotoMono.tar.xz"
	"Dejavusansm https://github.com/ryanoasis/nerd-fonts/releases/latest/download/DejaVuSansMono.tar.xz"
)

# Function to handle Ctrl+C
_error_handler() {
	echo -e "\nError detected or operation canceled by user (Ctrl+C)"
	rm -rf "$TMPDIR"
	exit 1
}

# Successful exit function
_exit_installer() {
	echo "Configuration for st+ completed, please restart it."
	rm -rf "$TMPDIR"
	exit 0
}

# Set trap for SIGINT (Ctrl+C)
trap _error_handler SIGINT

# Check for sudo or doas
if [ "$(id -u)" = 0 ] && [ -n "${SUDO_USER:-$DOAS_USER}" ]; then
	echo "ERROR: Do not use sudo/doas to execute this script."
	_error_handler
elif command -v sudo >/dev/null 2>&1; then
	SUDOCMD="sudo"
elif command -v doas >/dev/null 2>&1; then
	SUDOCMD="doas"
else
	echo "ERROR: No sudo or doas found"
	_error_handler
fi

# If uninstall/install was specified
if [ "$1" = "uninstall" ]; then
	# AppImage or make uninstall flow
	echo "This will uninstall st+ from your system."
	read -n 1 -rp "Press any key to continue or CTRL+C to cancel..."
	$SUDOCMD rm -f "$PREFIX"/bin/st+
	$SUDOCMD rm -f "$APPPREFIX"/st+.desktop
	$SUDOCMD rm -f "$MANPREFIX"/man1/st+.1
	$SUDOCMD rm -f "$NAUTILUS_EXT"/open-terminal.py
	# Remove fonts
	read -rp "Remove all st+ installed nerd-fonts? (y/n): " answer
	[[ "${answer^^}" == "Y" ]] && $SUDOCMD rm -rfv "${FONTPREFIX}"/*Nerd-ST
	# Check if st+ is installed via AM and trigger uninstall
	test -f /opt/st+/remove && am -R st+
	echo "All st+ related files have been removed. Please close all open st+ terminal sessions."
	exit 0
elif [ "$1" = "install" ]; then
	# make install flow
	[[ -n $APPDIR ]] && echo "ERROR: Incorrect option selected from within AppImage." && _error_handler
	$SUDOCMD mkdir -p  "$PREFIX"/bin
	$SUDOCMD cp -f st+ "$PREFIX"/bin || _error_handler
	$SUDOCMD chmod 755 "$PREFIX"/bin/st+
	$SUDOCMD mkdir -p  "$APPPREFIX"
	$SUDOCMD cp -f st+.desktop "$APPPREFIX"
else
	# AppImage config flow (copy $APPDIR contents to temp dir)
	[[ -z $APPDIR ]] && echo "ERROR: \$APPDIR variable is missing." && _error_handler
	mkdir -p "$TMPDIR"
	cp -rf "$APPDIR"/* "$TMPDIR"/.
	cd "$TMPDIR" || _error_handler
fi

# Install Gnome open-terminal extension
if [ ! -f "$NAUTILUS_EXT"/open-terminal.py ] && [ -d "$NAUTILUS_EXT" ]; then
	echo "Installing st+ Nautilus open-terminal integration..."
	$SUDOCMD cp -f open-terminal.py "$NAUTILUS_EXT"
fi

# Install manpage
if [ ! -f "$MANPREFIX"/man1/st+.1 ]; then
	echo "Installing st+ manpages..."
	$SUDOCMD mkdir -p "$MANPREFIX"/man1
	$SUDOCMD cp st+.1 "$MANPREFIX"/man1/st+.1
	$SUDOCMD chmod 644 "$MANPREFIX"/man1/st+.1
fi

# Install terminfo
if command -v infocmp >/dev/null 2>&1 && command -v tic >/dev/null 2>&1; then
	if ! infocmp st-256color > /dev/null 2>&1; then
		echo "Installing st+ terminfo..."
		$SUDOCMD tic -sx st.info
	fi
fi

# Print list of fonts to choose from
printf "\nRecommended fonts available for download (https://nerdfonts.com):\n"
for i in "${!fonts[@]}"; do
	echo "$((i+1)). ${fonts[$i]%% *}"
done

# Select font type
read -rp "Enter the number of the font to install (select 0 to skip): " choice
if [[ ! "$choice" =~ ^[0-9]+$ ]] || [ "$choice" -lt 1 ] || [ "$choice" -gt ${#fonts[@]} ]; then
	echo "Invalid selection, skipping font installation step."
	_exit_installer
fi
selected_font="${fonts[$((choice-1))]}"
font_name="${selected_font%% *}"
font_url="${selected_font##* }"
spaced_font_name="$(echo "$font_name" | sed 's/\([a-z]\)\([A-Z]\)/\1 \2/g') Nerd Font"

# Download and install font (if dir doesn't exist OR is at least 6 months old)
if [[ ! -d "${FONTPREFIX}/${font_name}Nerd-ST" ]] || find "${FONTPREFIX}/${font_name}Nerd-ST" -maxdepth 1 -type d -mtime +180 -print -quit | grep -q .; then
	wget -q --show-progress -c "$font_url" -O "${font_name}.tar.xz"
	printf "\nInstalling %s into %s...\n\n" "$spaced_font_name" "$FONTPREFIX"
	$SUDOCMD rm -rf "${FONTPREFIX}/${font_name}Nerd-ST"
	$SUDOCMD mkdir -p "${FONTPREFIX}/${font_name}Nerd-ST"
	$SUDOCMD tar xvf "${font_name}.tar.xz" -C "${FONTPREFIX}/${font_name}Nerd-ST" > /dev/null
	command -v fc-cache >/dev/null 2>&1 && fc-cache -fv >/dev/null 2>&1
else
	printf "\nSelected font is already installed recently, update not needed.\n\n"
fi

# Select font size to use
read -rp "Enter the font size to use: " font_size
if ! [[ "$font_size" =~ ^[0-9]+$ ]] || [ "$font_size" -lt 1 ] || [ "$font_size" -gt 50 ]; then
	echo "Invalid size, selecting default font size."
	font_size=14
fi

# Update ~/.st.conf notification
st+ -e exit >/dev/null 2>&1
sed -i "s/font=\"[^:]*:/font=\"${spaced_font_name}:/" ~/.st.conf
sed -i "s/pixelsize=[^:]*:/pixelsize=${font_size}:/" ~/.st.conf
printf "The st+ config file (~/.st.conf) has been updated to use font:\n\t ◆ \033[1m%s (size %s)\033[0m\n\n" "$spaced_font_name" "$font_size"

# End script
_exit_installer

