#!/bin/bash

# Variables (match it with config.mk)
PREFIX="/usr/local"
APPPREFIX="$PREFIX/share/applications"
MANPREFIX="$PREFIX/share/man"
FONTPREFIX="$PREFIX/share/fonts"
NAUTILUS_EXT="/usr/share/nautilus-python/extensions"
TMPDIR="/tmp/st-appdir.$RANDOM"

# Font list (format: "Name URL")
fonts=(
	"Firacode https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.tar.xz"
	"Firamono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.tar.xz"
	"Ubuntumono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.tar.xz"
	"LiterationMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/LiberationMono.tar.xz"
	"Caskaydiacove https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.tar.xz"
	"Caskaydiamono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.tar.xz"
	"Hack https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz"
	"Inconsolata https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Inconsolata.tar.xz"
	"Iosevka https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Iosevka.tar.xz"
	"Iosevkaterm https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IosevkaTerm.tar.xz"
	"Iosevkatermslab https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IosevkaTermSlab.tar.xz"
	"Jetbrainsmono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz"
	"Meslolgm https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.tar.xz"
	"Robotomono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/RobotoMono.tar.xz"
	"Dejavusansm https://github.com/ryanoasis/nerd-fonts/releases/latest/download/DejaVuSansMono.tar.xz"
)

# Color scheme names
scheme_names=("Gogh Color Scheme (browse collection at https://gogh-co.github.io/Gogh)" "Solarized Dark" "Solarized Light" "Monokai Dark" "Dracula" "Nord" "One Dark" "Tomorrow" "Tomorrow Night")

# All color scheme data
scheme_colors="073642 dc322f 859900 cf9a6b 268bd2 d33682 2aa198 eee8d5 657b83 cb4b16 859900 cf9a6b 6c71c4 d33682 2aa198 fdf6e3 002b36 839496 839496
eee8d5 dc322f 859900 b58900 268bd2 d33682 2aa198 002b36 657b83 cb4b16 859900 b58900 6c71c4 d33682 2aa198 073642 fdf6e3 657b83 657b83
75715e f92672 a6e22e f4bf75 66d9ef ae81ff 2aa198 f9f8f5 272822 f92672 a6e22e f4bf75 66d9ef ae81ff 2aa198 f8f8f2 272822 f8f8f2 f8f8f2
262626 e64747 42e66c e4f34a 9b6bdf e356a7 75d7ec f8f8f2 7a7a7a ff5555 50fa7b f1fa8c bd93f9 ff79c6 8be9fd f9f9fb 282a36 f8f8f2 f8f8f2
3b4252 bf616a a3be8c ebcb8b 81a1c1 b48ead 88c0d0 e5e9f0 4c566a bf616a a3be8c ebcb8b 81a1c1 b48ead 8fbcbb eceff4 2e3440 d8dee9 d8dee9
000000 e06c75 98c379 d19a66 61afef c678dd 56b6c2 abb2bf 5c6370 e06c75 98c379 d19a66 61afef c678dd 56b6c2 fffefe 1e2127 5c6370 5c6370
e0e0e0 c82829 718c00 eab700 4271ae 8959a8 3e999f 4d4d4c 8e908c c82829 718c00 eab700 4271ae 8959a8 3e999f 1d1f21 ffffff 4d4d4c 4d4d4c
282a2e cc6666 b5bd68 f0c674 81a2be b294bb 8abeb7 c5c8c6 969896 cc6666 b5bd68 f0c674 81a2be b294bb 8abeb7 ffffff 1d1f21 c5c8c6 c5c8c6"

# Function to handle Ctrl+C
_error_handler() {
	echo -e "\n ^ Error detected or operation canceled by user (Ctrl+C)"
	rm -rf "$TMPDIR"
	exit 1
}

# Successful exit function
_exit_config() {
	printf "\nConfiguration for st+ completed, please restart it.\n\n"
	rm -rf "$TMPDIR"
	exit 0
}

# Function to update color scheme
_setup_colors() {
	# Print list of color schemes
	printf "\nAvailable color schemes:\n"
	for i in "${!scheme_names[@]}"; do
		echo "$((i + 1)). ${scheme_names[$i]}"
	done
	echo && read -rp "Enter the number of the color scheme to use: " choice

	# Validate choice
	if [[ ! "$choice" =~ ^[0-9]+$ ]] || [ "$choice" -lt 1 ] || [ "$choice" -gt ${#scheme_names[@]} ]; then
		echo "Invalid choice, skipping color scheme setup."
		return 1
	fi

	# If Gogh was selected
	if [ "$choice" == 1 ]; then
		echo; read -rp "Key in selected Gogh color scheme (full name): " gogh
		wget --no-verbose --show-progress --progress=bar "https://raw.githubusercontent.com/Gogh-Co/Gogh/refs/heads/master/themes/$gogh.yml" || _error_handler
		scheme_colors=$(grep -o '#[0-9a-fA-F]\{6\}' "$gogh.yml" | sed 's/#//' | tr '\n' ' ' | tr '[:upper:]' '[:lower:]')
		local offset=0
		printf "\nUpdating color scheme to %s:\n ◆ %s\n\n" "$gogh" "$scheme_colors"
	else
		local offset=$((19*(choice - 2)))
		printf "\nUpdating color scheme to %s.\n\n" "${scheme_names[$choice - 1]}"
	fi

	# shellcheck disable=SC2206 # Split color string into array
	local -a colors=($scheme_colors)

	# Update primary 16 colors (indices 0-15)
	for i in {0..15}; do
		sed -i "s/^colorname\[$i\]=.*/colorname\[$i\]=\"\#${colors[$((i + offset))]}\"/" ~/.st.conf
	done

	# Update additional colors (indices 256-259)
	for i in {0..2}; do
		sed -i "s/^colorname\[$((i + 256))\]=.*/colorname\[$((i + 256))\]=\"\#${colors[$((i + offset + 16))]}\"/" ~/.st.conf
	done

	# Pause for any key
	read -n 1 -rp "Press any key to return or CTRL+C to exit..."
}

# Function to update color scheme
_setup_fonts() {
	# Print list of fonts to choose from
	printf "\nRecommended fonts available for download (https://nerdfonts.com):\n"
	for i in "${!fonts[@]}"; do
		echo "$((i+1)). ${fonts[$i]%% *}"
	done

	# Select font type
	echo && read -rp "Enter the number of the font to install: " choice
	if [[ ! "$choice" =~ ^[0-9]+$ ]] || [ "$choice" -lt 1 ] || [ "$choice" -gt ${#fonts[@]} ]; then
		echo "Invalid selection, skipping font installation step."
		return 1
	fi
	selected_font="${fonts[$((choice-1))]}"
	font_name="${selected_font%% *}"
	font_url="${selected_font##* }"
	spaced_font_name="$(echo "$font_name" | sed 's/\([a-z]\)\([A-Z]\)/\1 \2/g') Nerd Font"

	# Download and install font (if dir doesn't exist OR is at least 6 months old)
	if [[ ! -d "${FONTPREFIX}/${font_name}Nerd-ST" ]] || find "${FONTPREFIX}/${font_name}Nerd-ST" -maxdepth 1 -type d -mtime +180 -print -quit | grep -q .; then
		wget -q --show-progress -c "$font_url" -O "${font_name}.tar.xz"
		printf "\nInstalling %s into %s...\n\n" "$spaced_font_name" "$FONTPREFIX"
		$SUDOCMD rm -rf "${FONTPREFIX}/${font_name}Nerd-ST"
		$SUDOCMD mkdir -p "${FONTPREFIX}/${font_name}Nerd-ST"
		$SUDOCMD tar xvf "${font_name}.tar.xz" -C "${FONTPREFIX}/${font_name}Nerd-ST" > /dev/null
		command -v fc-cache >/dev/null 2>&1 && fc-cache -fv >/dev/null 2>&1
	else
		printf "\nSelected font is already installed recently, update not needed.\n\n"
	fi

	# Select font size to use
	read -rp "Enter the font size to use (default 14): " font_size
	if ! [[ "$font_size" =~ ^[0-9]+$ ]] || [ "$font_size" -lt 1 ] || [ "$font_size" -gt 50 ]; then
		echo "Invalid size, selecting default font size."
		font_size=14
	fi

	# Update ~/.st.conf
	st+ -e exit >/dev/null 2>&1
	sed -i "s/font=\"[^:]*:/font=\"${spaced_font_name}:/" ~/.st.conf
	sed -i "s/pixelsize=[^:]*:/pixelsize=${font_size}:/" ~/.st.conf
	printf "The st+ config file (~/.st.conf) has been updated to use font:\n\t ◆ \033[1m%s (size %s)\033[0m\n\n" "$spaced_font_name" "$font_size"

	# Pause for any key
	read -n 1 -rp "Press any key to return or CTRL+C to exit..."
}

# Function to install st+ extras
_setup_extras() {
	# Install Gnome open-terminal extension
	if [ ! -f "$NAUTILUS_EXT"/open-terminal.py ] && [ -d "$NAUTILUS_EXT" ]; then
		echo "Installing st+ Nautilus open-terminal integration..."
		$SUDOCMD cp -f open-terminal.py "$NAUTILUS_EXT"
	fi

	# Install manpage
	if [ ! -f "$MANPREFIX"/man1/st+.1 ]; then
		echo "Installing st+ manpages..."
		$SUDOCMD mkdir -p "$MANPREFIX"/man1
		$SUDOCMD cp st+.1 "$MANPREFIX"/man1/st+.1
		$SUDOCMD chmod 644 "$MANPREFIX"/man1/st+.1
	fi

	# Install terminfo
	if command -v infocmp >/dev/null 2>&1 && command -v tic >/dev/null 2>&1; then
		if ! infocmp st-256color > /dev/null 2>&1; then
			echo "Installing st+ terminfo..."
			$SUDOCMD tic -sx st.info
		fi
	fi

	# Pause for any key
	echo && read -n 1 -rp "Done. Press any key to return or CTRL+C to exit..."
}

# Function to uninstall st+ from the system
_uninstall_st() {
	# AppImage or make uninstall flow
	printf "\n\033[1mWARNING: This will uninstall st+ from your system !!!\033[0m\n\n"
	read -n 1 -rp "Press any key to continue or CTRL+C to cancel..."
	$SUDOCMD rm -f "$PREFIX"/bin/st+
	$SUDOCMD rm -f "$APPPREFIX"/st+.desktop
	$SUDOCMD rm -f "$MANPREFIX"/man1/st+.1
	$SUDOCMD rm -f "$NAUTILUS_EXT"/open-terminal.py
	# Remove fonts
	read -rp "Remove all st+ installed nerd-fonts? (y/n): " answer
	[[ "${answer^^}" == "Y" ]] && $SUDOCMD rm -rfv "${FONTPREFIX}"/*Nerd-ST
	# Check if st+ is installed via AM and trigger uninstall
	test -f /opt/st+/remove && am -R st+
	echo "All st+ related files have been removed. Please close all open st+ terminal sessions."
	exit 0
}

#####################################
### Main program starts from here ###
#####################################

# Set trap for SIGINT (Ctrl+C)
trap _error_handler SIGINT

# Check for sudo or doas
if [ "$(id -u)" = 0 ] && [ -n "${SUDO_USER:-$DOAS_USER}" ]; then
	echo "ERROR: Do not use sudo/doas to execute this command."
	_error_handler
elif command -v sudo >/dev/null 2>&1; then
	SUDOCMD="sudo"
elif command -v doas >/dev/null 2>&1; then
	SUDOCMD="doas"
else
	echo "ERROR: No sudo or doas found"
	_error_handler
fi

# If uninstall/install was specified
if [ "$1" = "uninstall" ]; then
	_uninstall_st
elif [ "$1" = "install" ]; then
	# make install flow
	[[ -n $APPDIR ]] && echo "ERROR: Incorrect option selected from within AppImage." && _error_handler
	$SUDOCMD mkdir -p  "$PREFIX"/bin
	$SUDOCMD cp -f st+ "$PREFIX"/bin || _error_handler
	$SUDOCMD chmod 755 "$PREFIX"/bin/st+
	$SUDOCMD mkdir -p  "$APPPREFIX"
	$SUDOCMD cp -f st+.desktop "$APPPREFIX"
else
	# AppImage config flow (copy $APPDIR contents to temp dir)
	[[ -z $APPDIR ]] && echo "ERROR: \$APPDIR variable is missing." && _error_handler
	mkdir -p "$TMPDIR"
	cp -rf "$APPDIR"/* "$TMPDIR"/.
	cd "$TMPDIR" || _error_handler
fi

# Start main menu
while true; do
clear
cat << 'EOF'

╔════════════════════════════════════════╗
║         ST+ CONFIGURATION MENU         ║
╚════════════════════════════════════════╝

EOF
printf "1. Color scheme configuration\n"
printf "2. Font configuration \033[1m(system-level)\033[0m\n"
printf "3. Manpage, terminfo, extension installation \033[1m(system-level)\033[0m\n"
printf "4. Uninstall st+ and installed files \033[1m(system-level)\033[0m\n"
printf "5. Exit st+ configurator\n\n"
read -rp "Enter your choice: " choice
case $choice in
	1) _setup_colors ;;
	2) _setup_fonts ;;
	3) _setup_extras ;;
	4) _uninstall_st ;;
	*) _exit_config ;;
esac
done

