#!/bin/bash

# Variables (match it with config.mk)
PREFIX="/usr/local"
APPPREFIX="$PREFIX/share/applications"
MANPREFIX="$PREFIX/share/man"
FONTPREFIX="$PREFIX/share/fonts"
NAUTILUS_EXT="/usr/share/nautilus-python/extensions"
TMPDIR="/tmp/st-appdir.$RANDOM"
APPDIR=${APPDIR:-"."}

# Font list (format: "Name URL")
fonts=(
	"CascadiaCode https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.tar.xz"
	"CascadiaMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.tar.xz"
	"DejaVuSansMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/DejaVuSansMono.tar.xz"
	"FiraCode https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.tar.xz"
	"FiraMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.tar.xz"
	"Hack https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz"
	"Inconsolata https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Inconsolata.tar.xz"
	"Iosevka https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Iosevka.tar.xz"
	"IosevkaTerm https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IosevkaTerm.tar.xz"
	"IosevkaTermSlab https://github.com/ryanoasis/nerd-fonts/releases/latest/download/IosevkaTermSlab.tar.xz"
	"JetBrainsMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz"
	"LiberationMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/LiberationMono.tar.xz"
	"Meslo https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Meslo.tar.xz"
	"RobotoMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/RobotoMono.tar.xz"
	"Ubuntu https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Ubuntu.tar.xz"
	"UbuntuMono https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.tar.xz"
)

# Exit function
_exit_installer() {
	echo "st+ post installation flow completed!"
	echo "Rerun it again to download a different font"
	rm -rf "$TMPDIR"
	exit 0
}

# Check for sudo of doas
if [ "$(id -u)" = 0 ] && [ -n "${SUDO_USER:-$DOAS_USER}" ]; then
	printf "\n Please do not use \"sudo\" to execute this script.\n\n"
	exit 1
elif command -v sudo >/dev/null 2>&1; then
	SUDOCMD="sudo"
elif command -v doas >/dev/null 2>&1; then
	SUDOCMD="doas"
else
	echo "ERROR: No sudo or doas found"
	exit 1
fi

# If clean/uninstall/install was specified
if [ "$1" = "clean" ]; then
    echo "Cleaning up st+ related files..."
	$SUDOCMD rm -f "$MANPREFIX"/man1/st+.1
	$SUDOCMD rm -f "$NAUTILUS_EXT"/open-terminal.py
    echo "You may now uninstall st+"
	exit 0
elif [ "$1" = "uninstall" ]; then
	$SUDOCMD rm -f "$PREFIX"/bin/st+
	$SUDOCMD rm -f "$APPPREFIX"/st+.desktop
	$SUDOCMD rm -f "$MANPREFIX"/man1/st+.1
	$SUDOCMD rm -f "$NAUTILUS_EXT"/open-terminal.py
	exit 0
elif [ "$1" = "install" ]; then
	$SUDOCMD mkdir -p  "$PREFIX"/bin
	$SUDOCMD cp -f st+ "$PREFIX"/bin
	$SUDOCMD chmod 755 "$PREFIX"/bin/st+
	$SUDOCMD mkdir -p  "$APPPREFIX"
	$SUDOCMD cp -f st+.desktop "$APPPREFIX"
fi

# Copy files to temp dir
mkdir -p "$TMPDIR"
cp -rf "$APPDIR"/* "$TMPDIR"/.
cd "$TMPDIR" || exit 1

# Install Gnome open terminal here extension
if [ -d "$NAUTILUS_EXT" ]; then
	$SUDOCMD cp -f open-terminal.py "$NAUTILUS_EXT";
else
	echo "Nautilus extension support not detected, skipping open-terminal install..."
fi

# Install manpage
$SUDOCMD sudo mkdir -p "$MANPREFIX"/man1
$SUDOCMD cp st+.1 "$MANPREFIX"/man1/st+.1
$SUDOCMD chmod 644 "$MANPREFIX"/man1/st+.1

# Install terminfo
$SUDOCMD tic -sx st.info

# Print list of fonts to choose from
printf "\nRecommended fonts available for download (https://nerdfonts.com):\n"
for i in "${!fonts[@]}"; do
    echo "$((i+1)). ${fonts[$i]%% *}"
done

# Process user input
read -rp "Enter the number of the font to install (select 0 to skip): " choice
if [[ ! "$choice" =~ ^[0-9]+$ ]] || [ "$choice" -lt 1 ] || [ "$choice" -gt ${#fonts[@]} ]; then
    echo "Invalid selection, skipping font installation step."
	_exit_installer
fi
selected_font="${fonts[$((choice-1))]}"
font_name="${selected_font%% *}"
font_url="${selected_font##* }"
spaced_font_name=$(echo "$font_name" | sed 's/\([a-z]\)\([A-Z]\)/\1 \2/g')

# Install font
wget -q --show-progress -c "$font_url" -O "${font_name}.tar.xz"
printf "\nInstalling %s into %s...\n\n" "$spaced_font_name" "$FONTPREFIX"
$SUDOCMD rm -rf "${FONTPREFIX}/${font_name}Nerd"
$SUDOCMD mkdir -p "${FONTPREFIX}/${font_name}Nerd"
$SUDOCMD tar xvf "${font_name}.tar.xz" -C "${FONTPREFIX}/${font_name}Nerd" > /dev/null

# Update ~/.st.conf notification
printf "Please update the st+ config file ~/.st.conf with new font name: \033[1m%s\033[0m\n\n" "$spaced_font_name"

# End script
_exit_installer

